version: '3.8'

services:
  frontend:
    image: ghcr.io/takenotes-app/notes-app:latest
    container_name: notes-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - notes-network

  backend:
    image: ghcr.io/takenotes-app/notes-app-backend:latest
    container_name: notes-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/notesapp
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - notes-network

  mongo:
    image: mongo:latest
    container_name: notes-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - notes-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  notes-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
